[build]
  publish = "."
  functions = "netlify/functions"
  command = ""

# --- 01-sem-espec ---
[[redirects]]
  from   = "/01-sem-espec/api/search"
  to     = "/.netlify/functions/search-01"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin  = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"
